FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["BasicConsumer.csproj", "BasicConsumer/"]
RUN dotnet restore "BasicConsumer/BasicConsumer.csproj"

WORKDIR /src/BasicConsumer
COPY . .
RUN dotnet build "BasicConsumer.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BasicConsumer.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:6.0 as base
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BasicConsumer.dll"]