FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["BasicProducer.csproj", "BasicProducer/"]
RUN dotnet restore "BasicProducer/BasicProducer.csproj"

WORKDIR /src/BasicProducer
COPY . .
RUN dotnet build "BasicProducer.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BasicProducer.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:6.0 as base
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BasicProducer.dll"]